# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build news-and-topics-management`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t news-and-topics-management`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system news-and-topics-management && \
          adduser --system -G news-and-topics-management news-and-topics-management

COPY dist/news-and-topics-management news-and-topics-management
RUN chown -R news-and-topics-management:news-and-topics-management .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix news-and-topics-management --omit=dev -f install

CMD [ "node", "news-and-topics-management" ]
